const AnnotationExample = require('./examples/annotation-example.js');
const InvoiceExample = require('./examples/invoice-example.js');
const TableExample = require('./examples/table-example.js');
const StackingExample = require('./examples/stacking-example.js');
const GridLayoutExample = require('./examples/grid-layout-example.js');
const ContainerExample = require('./examples/container-example.js');
const ImageExample = require('./examples/image-example.js');
const HeaderFooterExample = require('./examples/header-footer-example.js');
const BindingExample = require('./examples/binding-example.js');
const ChartExample = require('./examples/chart-example.js');
const CustomFontExample = require('./examples/custom-font-example.js');
const MultipleTemplateExample = require('./examples/multiple-template-example.js');

AnnotationExample.generate();
InvoiceExample.generate();
HeaderFooterExample.generate();
TableExample.generate();
StackingExample.generate();
GridLayoutExample.generate();
ContainerExample.generate();
ImageExample.generate();
BindingExample.generate();
ChartExample.generate();
CustomFontExample.generate();
MultipleTemplateExample.generate();
